### ISSUE TITLE
Server crash on first run 

### ISSUE THREAD

**Issue by cauliflower69** [squirrelkiller/SK-Utils#2]
http://pastebin.com/TeTGhUyb

**Comment by squirrelkiller** [comment]
Odd... I think it might have something to do with the forge version I use as I literally have an instance with that exact version of the mod open right now. Maybe if I update forge it will fix it. Should work in next patch.

**Comment by cauliflower69** [comment]
Thanks for looking into the issue

**Comment by squirrelkiller** [comment]
The next release should fix this, if not well then the problem was moved rather than fixed, as the entire part of the mod that is causing the crash has been traded out for a new system in the back end.

Just wait on curse to approve the file. If the issue is not resolved please just comment on this issue and I will reopen it.

**Comment by cauliflower69** [comment]
Just tried and now the crash is http://pastebin.com/M0aFr1yB

**Comment by squirrelkiller** [comment]
Fix one thing break twelve more, ok so it launches again on a server. I accidently had the mod running client code on the server. Also found a half other bugs in the process. Patched them. Sorry and thank you for your patience.

**Comment by cauliflower69** [comment]
Thanks again
